/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elevator;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Mark Masone
 */
public class ElevatorPanel extends javax.swing.JPanel {

    /**
     * Creates new form ElevatorPanel
     */
    public ElevatorPanel() {
        initComponents();
        highestFloor = 1;
        lowestFloor = 1;
        up = new boolean[]{false,false,false,false,false,false};
        down = new boolean[]{false,false,false,false,false,false};
        moving = false;
        direction = true;
        elevatorY = 375;
        upButtons = new javax.swing.JToggleButton[]{upButton1,upButton2,upButton3,upButton4,upButton5};
        downButtons = new javax.swing.JToggleButton[]{downButton2,downButton3,downButton4,downButton5,downButton6};
    }
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D)g;
        g2d.setColor(Color.red);
        g2d.drawRect(100, elevatorY, 150, 40);
        g2d.drawString("highest floor: " + highestFloor, 300, 60);
        g2d.drawString("lowest floor: " + lowestFloor, 300, 80);
        for(int i = 0; i < 6; i++) {
            int y = 80 + i * 64;
            g2d.drawString("up: " + up[5 - i], 150, y - 10);
            g2d.drawString("down: " + down[5 - i], 150, y + 10);
            g2d.drawString((6 - i) + "", 110, y);
        }
    }
    
    private void buttonPressed(int floor,boolean direction) {
        if(direction) {
            up[floor - 1] = true;
            upButtons[floor - 1].setEnabled(false);
        } else {
            down[floor - 1] = true;
            downButtons[floor - 2].setEnabled(false);
        }
        if(highestFloor < floor)
            highestFloor = floor;
        if(lowestFloor > floor)
            lowestFloor = floor;
        if(!moving)
            startElevator(true);
        repaint();
    }
    
    private void startElevator(boolean direction) {
        this.direction = direction;
        this.moving = true;
        timer = new Timer(); 
        task = new MoveElevator(this); 
        timer.schedule(task, 0, 20); 
    }
    
    public void moveElevator() {
        int floor = 6 - ((elevatorY + 7) / 64);
        if(direction && (up[floor - 1] || (floor == 6 && down[floor - 1]))) {
            task.cancel();
            timer.cancel();
            timer = new Timer();
            task = new MoveElevator(this);
            timer.schedule(task, 2000, 20);
            if(up[floor - 1]) { // up button pressed on this floor
                up[floor - 1] = false;
                upButtons[floor - 1].setSelected(false);
                upButtons[floor - 1].setEnabled(true);
            }
            if(floor == 6) { // top floor down button pressed
                down[floor - 1] = false;
                downButtons[floor - 2].setSelected(false);
                downButtons[floor - 2].setEnabled(true);
            }
        } else if(!direction && down[floor]) {
            task.cancel();
            timer.cancel();
            timer = new Timer();
            task = new MoveElevator(this);
            timer.schedule(task, 2000, 20);
            down[floor] = false;
            downButtons[floor - 1].setSelected(false);
            downButtons[floor - 1].setEnabled(true);
            elevatorY -= 1;
        } else if(!direction && floor == 0) {
            task.cancel();
            timer.cancel();
            moving = false;
            highestFloor = 1;
            elevatorY -= 1;
        } else {
            if(floor == highestFloor)
                direction = false;
            if(direction) {
                elevatorY -= 1;
            } else {
                elevatorY += 1;
            }
        }
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upButton1 = new javax.swing.JToggleButton();
        downButton6 = new javax.swing.JToggleButton();
        upButton5 = new javax.swing.JToggleButton();
        downButton5 = new javax.swing.JToggleButton();
        upButton4 = new javax.swing.JToggleButton();
        downButton4 = new javax.swing.JToggleButton();
        upButton3 = new javax.swing.JToggleButton();
        downButton3 = new javax.swing.JToggleButton();
        upButton2 = new javax.swing.JToggleButton();
        downButton2 = new javax.swing.JToggleButton();

        upButton1.setText("Up");
        upButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButton1ActionPerformed(evt);
            }
        });

        downButton6.setText("Down");
        downButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButton6ActionPerformed(evt);
            }
        });

        upButton5.setText("Up");
        upButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButton5ActionPerformed(evt);
            }
        });

        downButton5.setText("Down");
        downButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButton5ActionPerformed(evt);
            }
        });

        upButton4.setText("Up");
        upButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButton4ActionPerformed(evt);
            }
        });

        downButton4.setText("Down");
        downButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButton4ActionPerformed(evt);
            }
        });

        upButton3.setText("Up");
        upButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButton3ActionPerformed(evt);
            }
        });

        downButton3.setText("Down");
        downButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButton3ActionPerformed(evt);
            }
        });

        upButton2.setText("Up");
        upButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButton2ActionPerformed(evt);
            }
        });

        downButton2.setText("Down");
        downButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(downButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(upButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(upButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(downButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(upButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(downButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(upButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(downButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(upButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(downButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(331, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(downButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(downButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(downButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(downButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(downButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void downButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downButton6ActionPerformed
        buttonPressed(6,false);
    }//GEN-LAST:event_downButton6ActionPerformed

    private void downButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downButton5ActionPerformed
        buttonPressed(5,false);
    }//GEN-LAST:event_downButton5ActionPerformed

    private void upButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButton3ActionPerformed
        buttonPressed(3,true);
    }//GEN-LAST:event_upButton3ActionPerformed

    private void downButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downButton3ActionPerformed
        buttonPressed(3,false);
    }//GEN-LAST:event_downButton3ActionPerformed

    private void downButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downButton2ActionPerformed
        buttonPressed(2,false);
    }//GEN-LAST:event_downButton2ActionPerformed

    private void upButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButton5ActionPerformed
        buttonPressed(5,true);
    }//GEN-LAST:event_upButton5ActionPerformed

    private void upButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButton4ActionPerformed
        buttonPressed(4,true);
    }//GEN-LAST:event_upButton4ActionPerformed

    private void downButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downButton4ActionPerformed
        buttonPressed(4,false);
    }//GEN-LAST:event_downButton4ActionPerformed

    private void upButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButton2ActionPerformed
        buttonPressed(2,true);
    }//GEN-LAST:event_upButton2ActionPerformed

    private void upButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButton1ActionPerformed
        buttonPressed(1,true);
    }//GEN-LAST:event_upButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton downButton2;
    private javax.swing.JToggleButton downButton3;
    private javax.swing.JToggleButton downButton4;
    private javax.swing.JToggleButton downButton5;
    private javax.swing.JToggleButton downButton6;
    private javax.swing.JToggleButton upButton1;
    private javax.swing.JToggleButton upButton2;
    private javax.swing.JToggleButton upButton3;
    private javax.swing.JToggleButton upButton4;
    private javax.swing.JToggleButton upButton5;
    // End of variables declaration//GEN-END:variables
    private int highestFloor;
    private int lowestFloor;
    private boolean[] up;
    private boolean[] down;
    private boolean moving;
    private boolean direction;
    private int elevatorY;
    private Timer timer;
    private TimerTask task;
    private javax.swing.JToggleButton[] upButtons;
    private javax.swing.JToggleButton[] downButtons;
}
