/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elevator;

import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JToggleButton;

/**
 *
 * @author Mark Masone
 */
public class SimulatorPanel extends javax.swing.JPanel implements FloorRequestListener,ElevatorMovementListener {

    /**
     * Creates new form ElevatorPanel
     */
    
    private final ElevatorShaft elevatorShaft;
    private final Elevator elevator;
    
    public SimulatorPanel(ElevatorShaft elevatorShaft,Elevator elevator) {
        initComponents();
        elevatorShaft.setButtons(
            new JToggleButton[]{upButton1,upButton2,upButton3,upButton4,upButton5},
            new JToggleButton[]{downButton2,downButton3,downButton4,downButton5,downButton6}
        );
        elevator.setButtons(new JToggleButton[]{floor1Button,floor2Button,floor3Button,floor4Button,floor5Button,floor6Button});
        this.elevatorShaft = elevatorShaft;
        this.elevator = elevator;
    }
    
    @Override
    public void floorRequested(int floor) {
        repaint();
    }
    
    @Override
    public void elevatorMoved() {
        repaint();
    }
    
    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D)g;
        elevator.draw(g2d);
        elevatorShaft.draw(g2d);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upButton1 = new javax.swing.JToggleButton();
        downButton6 = new javax.swing.JToggleButton();
        upButton5 = new javax.swing.JToggleButton();
        downButton5 = new javax.swing.JToggleButton();
        upButton4 = new javax.swing.JToggleButton();
        downButton4 = new javax.swing.JToggleButton();
        upButton3 = new javax.swing.JToggleButton();
        downButton3 = new javax.swing.JToggleButton();
        upButton2 = new javax.swing.JToggleButton();
        downButton2 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        floor6Button = new javax.swing.JToggleButton();
        floor5Button = new javax.swing.JToggleButton();
        floor4Button = new javax.swing.JToggleButton();
        floor3Button = new javax.swing.JToggleButton();
        floor2Button = new javax.swing.JToggleButton();
        floor1Button = new javax.swing.JToggleButton();

        upButton1.setText("Up");
        upButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButton1ActionPerformed(evt);
            }
        });

        downButton6.setText("Down");
        downButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButton6ActionPerformed(evt);
            }
        });

        upButton5.setText("Up");
        upButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButton5ActionPerformed(evt);
            }
        });

        downButton5.setText("Down");
        downButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButton5ActionPerformed(evt);
            }
        });

        upButton4.setText("Up");
        upButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButton4ActionPerformed(evt);
            }
        });

        downButton4.setText("Down");
        downButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButton4ActionPerformed(evt);
            }
        });

        upButton3.setText("Up");
        upButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButton3ActionPerformed(evt);
            }
        });

        downButton3.setText("Down");
        downButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButton3ActionPerformed(evt);
            }
        });

        upButton2.setText("Up");
        upButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButton2ActionPerformed(evt);
            }
        });

        downButton2.setText("Down");
        downButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        floor6Button.setText("6");
        floor6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor6ButtonActionPerformed(evt);
            }
        });

        floor5Button.setText("5");
        floor5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor5ButtonActionPerformed(evt);
            }
        });

        floor4Button.setText("4");
        floor4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor4ButtonActionPerformed(evt);
            }
        });

        floor3Button.setText("3");
        floor3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor3ButtonActionPerformed(evt);
            }
        });

        floor2Button.setText("2");
        floor2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor2ButtonActionPerformed(evt);
            }
        });

        floor1Button.setText("1");
        floor1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor1ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(floor2Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(floor3Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(floor4Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(floor5Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(floor6Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(floor1Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(floor6Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(floor5Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(floor4Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(floor3Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(floor2Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(floor1Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(downButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(upButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(upButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(downButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(upButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(downButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(upButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(downButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(upButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(downButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(217, 217, 217)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(downButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(downButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(upButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(downButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(upButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(downButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(upButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(downButton2))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void downButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downButton6ActionPerformed
        elevatorShaft.buttonPressed(6,false);
    }//GEN-LAST:event_downButton6ActionPerformed

    private void downButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downButton5ActionPerformed
        elevatorShaft.buttonPressed(5,false);
    }//GEN-LAST:event_downButton5ActionPerformed

    private void upButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButton3ActionPerformed
        elevatorShaft.buttonPressed(3,true);
    }//GEN-LAST:event_upButton3ActionPerformed

    private void downButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downButton3ActionPerformed
        elevatorShaft.buttonPressed(3,false);
    }//GEN-LAST:event_downButton3ActionPerformed

    private void downButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downButton2ActionPerformed
        elevatorShaft.buttonPressed(2,false);
    }//GEN-LAST:event_downButton2ActionPerformed

    private void upButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButton5ActionPerformed
        elevatorShaft.buttonPressed(5,true);
    }//GEN-LAST:event_upButton5ActionPerformed

    private void upButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButton4ActionPerformed
        elevatorShaft.buttonPressed(4,true);
    }//GEN-LAST:event_upButton4ActionPerformed

    private void downButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downButton4ActionPerformed
        elevatorShaft.buttonPressed(4,false);
    }//GEN-LAST:event_downButton4ActionPerformed

    private void upButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButton2ActionPerformed
        elevatorShaft.buttonPressed(2,true);
    }//GEN-LAST:event_upButton2ActionPerformed

    private void upButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButton1ActionPerformed
        elevatorShaft.buttonPressed(1,true);
    }//GEN-LAST:event_upButton1ActionPerformed

    private void floor6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor6ButtonActionPerformed
        elevator.buttonPressed(6);
    }//GEN-LAST:event_floor6ButtonActionPerformed

    private void floor5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor5ButtonActionPerformed
        elevator.buttonPressed(5);
    }//GEN-LAST:event_floor5ButtonActionPerformed

    private void floor4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor4ButtonActionPerformed
        elevator.buttonPressed(4);
    }//GEN-LAST:event_floor4ButtonActionPerformed

    private void floor3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor3ButtonActionPerformed
        elevator.buttonPressed(3);
    }//GEN-LAST:event_floor3ButtonActionPerformed

    private void floor2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor2ButtonActionPerformed
        elevator.buttonPressed(2);
    }//GEN-LAST:event_floor2ButtonActionPerformed

    private void floor1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor1ButtonActionPerformed
        elevator.buttonPressed(1);
    }//GEN-LAST:event_floor1ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton downButton2;
    private javax.swing.JToggleButton downButton3;
    private javax.swing.JToggleButton downButton4;
    private javax.swing.JToggleButton downButton5;
    private javax.swing.JToggleButton downButton6;
    private javax.swing.JToggleButton floor1Button;
    private javax.swing.JToggleButton floor2Button;
    private javax.swing.JToggleButton floor3Button;
    private javax.swing.JToggleButton floor4Button;
    private javax.swing.JToggleButton floor5Button;
    private javax.swing.JToggleButton floor6Button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton upButton1;
    private javax.swing.JToggleButton upButton2;
    private javax.swing.JToggleButton upButton3;
    private javax.swing.JToggleButton upButton4;
    private javax.swing.JToggleButton upButton5;
    // End of variables declaration//GEN-END:variables
}
